# Generated by Django 5.0.6 on 2024-07-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
