# Generated by Django 5.0.7 on 2024-07-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
