# Generated by Django 5.0.7 on 2024-10-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
