# Generated by Django 5.0.7 on 2024-10-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_chatmessage_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_time',
        ),
    ]
