# Generated by Django 5.0.7 on 2024-10-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_remove_chatmessage_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
